name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install Prisma CLI
        run: npm install -g prisma

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Set up Prisma
        run: |
          npx prisma generate
          npx prisma migrate deploy

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Deploying to production server..."
          # Add your deployment commands here
